### ISSUE TITLE
Why Mortar needs to add the "Ghost View" when I use VFL to define layout?

### ISSUE THREAD

**Issue by maximkhatskevich** [jmfieldman/Mortar#26]
@jmfieldman I am just curious, why we need to add the "Ghost View" to the view hierarchy when defining its layout with VFL? Why we need "Ghost View" at all? Is it some kind of simplification or workaround for a complex problem you couldn't solve otherwise? I tried to look into source code, but couldn't figure out why exactly we need it, why it's not possible to do the job without implicitly adding anything to given view hierarchy? I'd appreciate if you share some insights with me. Thanks!

P.S. Thanks a lot for the library, it's amazing! I'm switching on Mortar from SnapKit and super happy with it.

**Comment by jmfieldman** [comment]
@maximkhatskevich in my experience there is no way to get ratio-based sizing between views (without adding an additional view).  For example, if you want something like:

[view1][space][view2][space][view3]

Where all elements are the same width, you can't get dynamically sized between-view space like that (that will scale cleanly w/ autolayout).  Perhaps anchors can do this (?) but I don't much experience with those (which is why I used a ghost view).

You can see that the only place I add a ghost view is when a VFL node is ratio-based and does not include a view (e.g. it is an empty ratio-based VFL node).

**Comment by jmfieldman** [comment]
P.S. Glad you like the library! :)

**Comment by maximkhatskevich** [comment]
@jmfieldman so you use the ghost view as reference view with size value for given axis equal to "~~1", and then constrain other views in the same VFL expression along this axis to this reference view, with a multiplier equal to their weighted size?

**Comment by jmfieldman** [comment]
Rather, I determine all of the ratios first.  So ~~1 | ~~2 | ~~3 would be 1/6, 2/6, 3/6.  I can then assign each view their specific ratio of the parent width.  Then each view can be linked to the ones next to it w/ leading/trailing edges.  Since raw space can't be ratio-based it needs to be a ghost view :(

**Comment by maximkhatskevich** [comment]
Okay, I see. I guess this approach came from the fact that leading and trailing views can potentially be different views, right? When it's the same view (when we use "|^^" or "|>>", etc.) - we could just use this view itself as a reference and do not add a ghost view if I understand everything correctly? What do you think?

**Comment by maximkhatskevich** [comment]
Oh, wait, or do you mean the ghost views are actually empty space placeholders at the positions where I put weighted space in VFL expression?

**Comment by jmfieldman** [comment]
The latter -- the ghost views take the empty ratio space in the VFL expression

**Comment by jmfieldman** [comment]
Also w/ this method it doesn't really matter which autolayout view+edge combos are the "parent edges" for the VFL expression.  There will simply be some parent left/right or top/bottom edges that have some scalable space S between them.  We set all the ratio views inside S to have width/height relative to each other.

**Comment by maximkhatskevich** [comment]
@jmfieldman okay, thanks for the info. I think that's enough info for me for now. Appreciate your time!
